### ISSUE TITLE
Unexpected top-level exception when running app

### ISSUE THREAD

**Issue by zsoltk** [nenick/android-gradle-template#23]
Hello,

After installation (I left everything as is) I get this exception when trying to run App:

Error:Execution failed for task ':App:preDexIntegrationDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/.../.../android-sdk/build-tools/android-4.4W/dx --dex --output /home/.../.../.../App/build/intermediates/pre-dexed/integration/debug/GenerateJsonRestModel-2efcc7932f87b8eeed5d2afe940f5caf68cb17e6.jar /home/.../.../.../GenerateJsonRestModel/build/libs/GenerateJsonRestModel.jar
  Error Code:
  	1
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
  		at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
  		at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
  		at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
  		at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
  		at com.android.dx.command.dexer.Main.processClass(Main.java:665)
  		at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
  		at com.android.dx.command.dexer.Main.access$600(Main.java:78)
  		at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
  		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
  		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
  		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
  		at com.android.dx.command.dexer.Main.processOne(Main.java:596)
  		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
  		at com.android.dx.command.dexer.Main.run(Main.java:230)
  		at com.android.dx.command.dexer.Main.main(Main.java:199)
  		at com.android.dx.command.Main.main(Main.java:103)
  	...while parsing com/example/json/Bookmark.class
  	1 error; aborting

The strange thing is, everyhing is ok if I only build it. This exception arises only when I try to run it.

I tried googling, nothing relevant came up. Any idea on how to solve this would be greatly appreciated.

Thanks!

**Comment by zsoltk** [comment]
It turns out that it all boils down to the @Generated annotation in Bookmark.java being added by jsonschema2pojo.

The @Generated annotation is referenced from the Java SDK. Now, I had Java 8. After installing Java 7 as well and setting the Java SDK location to its folder in the Project properties, the exception is gone and I can compile the project. I hope this info helps others as well.

**Comment by nenick** [comment]
Thanks for pointing it out.
